# Generated by Django 4.0.1 on 2022-01-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('no', models.IntegerField(verbose_name='No')),
                ('height', models.IntegerField(verbose_name='高さ')),
                ('weight', models.IntegerField(verbose_name='重さ')),
                ('order', models.IntegerField(verbose_name='並び順')),
                ('is_default', models.BooleanField(verbose_name='デフォルトフォルム')),
                ('created_at', models.DateTimeField(verbose_name='登録日')),
            ],
            options={
                'verbose_name': 'ポケモン',
                'verbose_name_plural': 'ポケモン',
                'db_table': 'pokeomn',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PokemonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.CharField(max_length=5, verbose_name='ポケモンID')),
                ('local_language_id', models.IntegerField(verbose_name='言語')),
                ('name', models.CharField(max_length=10, verbose_name='ポケモン名')),
                ('form_name', models.CharField(max_length=20, verbose_name='フォルム名')),
                ('pokemon_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon', verbose_name='ポケモン')),
            ],
            options={
                'verbose_name': 'ポケモン名',
                'verbose_name_plural': 'ポケモン名',
                'db_table': 'pokemon_name',
                'ordering': ['pokemon_id', 'local_language_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pokemonname',
            constraint=models.UniqueConstraint(fields=('pokemon_id', 'local_language_id'), name='unique_pokemon_name'),
        ),
    ]
