# Generated by Django 4.0.1 on 2022-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonname',
            name='form_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='フォルム名'),
        ),
    ]
