# Generated by Django 4.0.1 on 2022-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonname',
            options={'ordering': ['pokemon_id', 'local_language_id'], 'verbose_name': 'ポケモン名', 'verbose_name_plural': 'ポケモン名'},
        ),
        migrations.RemoveConstraint(
            model_name='pokemonname',
            name='unique_pokemon_name',
        ),
        migrations.AlterField(
            model_name='pokemonname',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='pokemonname',
            constraint=models.UniqueConstraint(fields=('pokemon_id', 'local_language_id'), name='unique_pokemon_name'),
        ),
    ]
