# Generated by Django 4.0.1 on 2022-02-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pokemonname_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table='pokemon',
        ),
    ]
